### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by frcol** [jenius/atom-fold-comments#15]
I´ve installed the package, but when I press CTRL+SHIFT+/ nothing happens.

**Comment by jescalan** [comment]
Unable to replicate this issue, it's working perfectly fine for me in the latest version of atom. Would need more info to be able to help here.

**Comment by frcol** [comment]
Any tip? I´ll try to remove and install again.

**Comment by jescalan** [comment]
I'm sorry, but I really have no idea. I don't think this is an issue with the plugin though, as nobody else is having this problem, it's likely something to do with your machine or atom installation...

**Comment by frcol** [comment]
It´s working now. I really don´t know what happened. It´s very useful for ngDocs.
Thanks!
