### ISSUE TITLE
TextEditor.get is deprecated.

### ISSUE THREAD

**Issue by skarfacegc** [jenius/atom-fold-comments#16]
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.get (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/text-editor.js:105:14)
<unknown> (/Users/andrew/.atom/packages/fold-comments/lib/fold-comments.coffee:32:26)
Workspace.observeTextEditors (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:9)
Object.activate (/Users/andrew/.atom/packages/fold-comments/lib/fold-comments.coffee:30:31)
Package.activateNow (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/package.js:218:19)
<unknown> (/opt/homebrew-cask/Caskroom/atom/1.5.3/Atom.app/Contents/Resources/app.asar/src/package.js:876:25)
```

**Comment by jescalan** [comment]
Hey @skarfacegc - thanks for the heads up on this! Would you be interested in submitting a PR to fix this?

**Comment by skarfacegc** [comment]
Just sent this along from that atom deprecation warning.  I haven't done any atom dev, so the message was a bit cryptic to me.

**Comment by jescalan** [comment]
Honestly I haven't messed with this plugin for a while, so it's cryptic to me as well. I'll take a look when I have a chance though!
