### ISSUE TITLE
TextEditor.displayBuffer is deprecated.

### ISSUE THREAD

**Issue by pavelkukov** [jenius/atom-fold-comments#20]
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.displayBuffer (<embedded>:2601:16)
<unknown> (C:\Users\work\.atom\packages\fold-comments\lib\fold-comments.coffee:32:26)
Workspace.observeTextEditors (<embedded>:28163:15)
Object.activate (C:\Users\work\.atom\packages\fold-comments\lib\fold-comments.coffee:30:31)
Package.activateNow (<embedded>:72535:25)
<unknown> (<embedded>:73302:31)
```

**Comment by jescalan** [comment]
Hey there @pavelkukov! To be honest, while I made this quite a long time ago, I am not using or maintaining it actively. If you feel like you can fix it, I would very much welcome a pull request to do so though!
