### ISSUE TITLE
TextEditor.displayBuffer is deprecated.

### ISSUE THREAD

**Issue by jcmunozmora** [jenius/atom-fold-comments#23]
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.displayBuffer (<embedded>:2481:16)
<unknown> (/Users/juan-carlosm/.atom/packages/fold-comments/lib/fold-comments.coffee:32:27)
Workspace.observeTextEditors (<embedded>:28726:59)
Object.activate (/Users/juan-carlosm/.atom/packages/fold-comments/lib/fold-comments.coffee:30:31)
Package.activateNow (<embedded>:74366:33)
activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (<embedded>:75001:28)
```

**Comment by jescalan** [comment]
Hi @jcmunozmora! This issue has been [opened](https://github.com/jescalan/atom-fold-comments/issues/20) [several](https://github.com/jescalan/atom-fold-comments/issues/22) [times](https://github.com/jescalan/atom-fold-comments/issues/21) already. I am not actively maintaining this package anymore, so if you'd like this resolved, you will have to contribute.
