### ISSUE TITLE
TextEditor.displayBuffer is deprecated.

### ISSUE THREAD

**Issue by arthur-eudeline** [jenius/atom-fold-comments#24]
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.displayBuffer (<embedded>:6:61)
<unknown> (/Users/arthur-eudeline/.atom/packages/fold-comments/lib/fold-comments.coffee:32:27)
Workspace.observeTextEditors (<embedded>:11:425358)
Object.activate (/Users/arthur-eudeline/.atom/packages/fold-comments/lib/fold-comments.coffee:30:31)
Package.activateNow (<embedded>:11:2955469)
activationCommandSubscriptions.add.commandRegistry.onWillDispatch.n (<embedded>:14:1717)
```

**Comment by jescalan** [comment]
This issue has been opened [several times already](https://github.com/jescalan/atom-fold-comments/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed). I am not actively maintaining this package anymore, so if you'd like this resolved, you will have to contribute.

**Comment by arthur-eudeline** [comment]
@jescalan I did not know, sorry for the inconvenience it's Atom who redirected me here, thanks for your job in any case !
