### ISSUE TITLE
TextEditor.displayBuffer is deprecated.

### ISSUE THREAD

**Issue by asweta-io** [jenius/atom-fold-comments#26]
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.displayBuffer (<embedded>:6:61)
<unknown> (C:\Users\Dweep\.atom\packages\fold-comments\lib\fold-comments.coffee:32:27)
Workspace.observeTextEditors (<embedded>:11:428231)
Object.activate (C:\Users\Dweep\.atom\packages\fold-comments\lib\fold-comments.coffee:30:31)
Package.activateNow (<embedded>:11:3538985)
activationCommandSubscriptions.add.commandRegistry.onWillDispatch.o (<embedded>:14:1717)
```

**Comment by jescalan** [comment]
Dupe: https://github.com/jescalan/atom-fold-comments/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed
