### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by pwalker91** [jenius/atom-fold-comments#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Utilities (Other)/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/peterwalker/.atom/packages/fold-comments/lib/fold-comments.coffee:3:9)
```

**Comment by jenius** [comment]
Thanks for finding this and sending in a PR. Just shipped a new version with your changes!
