### ISSUE TITLE
Selectively fold comments

### ISSUE THREAD

**Issue by CMCDragonkai** [jenius/atom-fold-comments#5]
Could it be possible to selectively fold comments?

**Comment by jenius** [comment]
I don't understand what you mean here

**Comment by CMCDragonkai** [comment]
Instead of folding all the comments in a document, only fold specific ones you want to fold.

**Comment by jenius** [comment]
You can do this by just folding the comments yourself. If you go over to the sidebar, there is a little arrow you can click to manually fold a line. If you are just trying to fold specific comments, you can do it manually. If you are looking for some sort of complex system that runs a formula to select specific comments or remembers which ones you folded etc, that is out of scope for this plugin, but I think another plugin that did this would be just wonderful!
